version: '3'

services:
  test-ts-app-cli:
    image: dmitryl12345/pub_test:latest
    container_name: test-ts-app-cli-exec
    # restart: unless-stopped
    environment:
      - PORT=3000
    ports:
      - "127.0.0.1:4000:3000"
    volumes:
      - ./:/usr/src/app
    command: node lib/index.js
